sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t matthv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true matthv/react-test npm test

after_success:
  - docker build -t matthv/multi-client ./client
  - docker build -t matthv/multi-nginx ./nginx
  - docker build -t matthv/multi-server ./server
  - docker build -t matthv/multi-worker ./worker
  # first log to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push matthv/multi-client
  - docker push matthv/multi-nginx
  - docker push matthv/multi-server
  - docker push matthv/multi-worker

deploy:
  provider: eslaticbeanstalk
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-392816299188'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
